# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
on:
  push:
    branches:
      - vq-chat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          run_install: false
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Output NPM Key
        run: echo "NODE_AUTH_TOKEN=${{ secrets.NPM_KEY }}"
      - name: Output ABC
        run: echo "NODE_AUTH_TOKEN=${{ secrets.ABC }}"
